server:
  port: 8000
  servlet:
    context-path: /moechat

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/moechat?serverTimezone=Asia/Shanghai
    username: root
    password: Aa778899
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  typeAliasesPackage: com.chanshiyu.mbg.entity

netty:
  socket:
    port: 8001
  websocket:
    port: 8002

logging:
  level:
    com.chanshiyu.api: debug

jwt:
  tokenHeader: Authorization
  tokenHead: Bearer
  secret: moechat-secret
  expiration: 604800

swagger:
  title: Moechat
  description: Moe moe chat!
  version: 1.0.0
  terms-of-service-url: https://chanshiyu.com/
  base-package: com.chanshiyu.api
  base-path: /**
  contact:
    name: 蝉時雨
    url: https://chanshiyu.com/
    email: me@chanshiyu.com
  authorization:
    name: Authorization
    type: ApiKey
    key-name: token
    auth-regex: ^.*$